# Generated by Django 3.1 on 2020-08-30 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Devices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostName', models.CharField(max_length=20)),
                ('IPAddress', models.CharField(max_length=20)),
                ('deviceType', models.CharField(max_length=20)),
                ('series', models.CharField(max_length=20)),
                ('lastScanned', models.DateField()),
            ],
        ),
    ]
