# Generated by Django 3.1 on 2020-08-31 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0002_auto_20200830_1230'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='model',
            field=models.CharField(default='', max_length=20),
        ),
    ]
