# Generated by Django 3.1 on 2020-08-31 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0003_device_model'),
    ]

    operations = [
        migrations.RenameField(
            model_name='device',
            old_name='series',
            new_name='family',
        ),
    ]
